"""
User role defines the permission of a user to perform certain operations.
"""
enum USER_ROLE {
  "Unauthenticated user. Capable of requesting general data. Cannot edit anything."
  VISITOR

  "Capable of publishing new content and editing the content of personal authorship."
  EDITOR

  "Capable of reviewing and editing the content of another users."
  PUBLISHER

  "Administrator. Basically, a semi-god."
  ADMIN
}
