type Song {
  artistId: ID!
  artist: Artist!
  title: String!
  country: String
  releaseDate: Date
  explicit: Boolean!
  price: Float!
}

extend type Query {
  search(term: String!, first: Int): [Song!]
}
