type Song {
  id: ID!
  trackNumber: Int!
  title: String!
  duration: Int!
  explicit: Boolean!
  price: Float
  releaseDate: Date
  albumId: ID!
  artistId: ID!
  artist: Artist!
  country: String
}

extend type Query {
  songs(albumId: ID!): [Song]
}
