# Search can return both artist or album
union MixedResults = Artist | Album

extend type Query {
  search(
    term: String!
    entity: SearchEntityType
    media: SearchMediaType
    limit: Int
  ): [MixedResults]

  lookup(
    id: ID
    term: String
    entity: SearchEntityType
    limit: Int
  ): MixedResults
}
