type User {
  # Private
  id: ID!
  role: UserRole!
  email: Email!
  password: String!

  # Public
  firstName: String!
  lastName: String!
  createdAt: Date!
}

type LoginRes {
  token: String!
  firstName: String!
  lastName: String!
}

extend type Query {
  login(email: Email!, password: String!): LoginRes
  user(id: Int!): User!
  users: [User!]
}
