type User {
  id: ID!
  role: UserRole!
  email: Email!
  password: String!
  createdAt: Date!
  firstName: String!
  lastName: String!
}

extend type Query {
  user(id: Int!): User!
  users: [User!]
}
